### ISSUE TITLE
How to use with 3phase without "zero" line

### ISSUE THREAD

**Issue by KLucky13** [svenakela/ha#3]
Hi,

I was wondering if this automation can be properly used with 3phase connections without a "zero" line. In a lot of parts of Belgium we have connections where you only have 3 live wires (you measure 220v between every wire). Also known as a "Three-Phase Delta(Δ) Configuration". My P1 port still gives out a L1, L2 and L3 value, however, on the L2 line, I never measure any current. 

My main fuse is 25A, but this cannot be seen as 25A over 3 lines (as you can understand from the three phase delta and how it works). So in reality, with a 25A connection, I have about 10kw available while a normal 3phase connection at 25A would be around 17kw.

I can see that the blueprint adapts the max available current on the charger, that's not the problem, it's just that the estimations of the exact available power are wrong. Anything that could be done to account for this?

I have a Tesla Model Y, Tesla is one of the few electric cars that can take full advantage of a three phase delta connection. 

Here you have the calculation for that:

![image](https://github.com/svenakela/ha/assets/16277786/62b0f862-419b-4126-baf0-639aadcc1f3a)

**Comment by KLucky13** [comment]
@svenakela any change you could have a look at how this can be included? That would be great

**Comment by svenakela** [comment]
All 3 phase motors above 4kW is required a Y/D starter, hence all countries in Europe use delta in one way or another. But there are some weird countries out there that took it too far. Yours, and Norway for example. :smile: 

I need to look at it during the weekend, but I can't see right now why it shouldn't work as is. The balancer uses threshold values to adjust the max current, what those thresholds are set to doesn't really matter from a balancing point of view.

**Comment by KLucky13** [comment]
@svenakela I'm not sure but when I fill in that my main fuse is 25Amps, it just does not lower the available power to the car once I reach my max. Like I said, L1 and L3 will show data where L2 does not show any activity on my smart meter. 

So if it thinks that there is 25Amps available on L1 and L3, that would be (correct me if I'm wrong):

L1 = 25A x 230 V = 5750 watts
L3 = 25A x 230 V = 5750 watts 

=> 11.500 watts in total. While in reality I only have slightly less than 10kw available.

That said, I think something else might be wrong too since yesterday my mine fuse blew at 13kW when my wife started up the furnace while the car was charging at 9kW. Your blueprint was active, so it might be that something else is also not working as it should.

**Comment by svenakela** [comment]
The blueprint is reading all three phases but will react if _any_ of those three are passing the limit. In your case it doesn't matter if there are only values on L1 and L3 - as long as L2 isn't used. If anything over charges L2 we are helpless in this scenario (what you can't see you can't fix).

I think the solution is rather simple. You should lower your main and charger fuse values to suite your actual system. Even though you have 25 A in the main central. If you blow fuses at 21 A current draw, set the main to 20. Or similar values that reflects your reality.

The balancing logic is not computing a value for each phase. _All three phases_ must be set to the same limit value simultaneously. This is how the charging standard works for all three phase chargers and the balancing is doing what the standard states.

**Comment by KLucky13** [comment]
Hi, thanks, I will check again next time the car is charging, something is not working as it is supposed to work, if the main fuse blew at a total of 13kw, then the seperate phases must have been over 25A for sure, but maybe I'm missing something. Next time the car is charging I'll have a look at the seperate phase load etc
