### ISSUE TITLE
Feature request: "Solar only charging"

### ISSUE THREAD

**Issue by Ghannes** [svenakela/ha#7]
Would be great to have the option to limit the charging current to the overproduction of a solar-set.

E.g. In The Netherlands we will get additional costs for the overproduction of elektric energy we put in the grid. Therefor I'd like to charge with the overproduction only.

**Comment by svenakela** [comment]
That can be done already by limiting the Zaptec integration, no need to change the load balancer for that.
Also, in a software system you want to keep components isolated and responsible for one task (SOLID principle). The load balancer should do load balancing, no more no less.
